export const products = [
    {
        img: 'Image.png',
        imgAlt: 'type',
        desc: 'Vintage Typewriter to post asewsome stories about UI design and webdev',
        price: '$49.50',
        note: 'Eligible for Shipping To Mars or somewhere else',
        rating: '4.05',
    },
     {
        img: 'boots.png',
        imgAlt: 'boots',
        desc: 'Lee Pucker design. Leather botinki for handsome designers. Free shipping',
        price: '$13.95',
        note: '1258 bids, 359 watchers $5.95 for shipping',
        rating: '4.56',
    },
    {
        img: 'cat.png',
        imgAlt: 'cat',
        desc: 'Timesaving kitten to save months on development. Playful, cute, cheap!',
        price: '$128.99',
        note: 'Eligible for nothing :(',
        rating: '4.87',
    },
    {
        img: 'plastic.png',
        imgAlt: 'plastic',
        desc: 'Plastic useless plugs and tubes for high-fidelity prototyping. Fit & Eat!',
        price: '$12.48',
        note: 'Worldwide shitting available. Buyers protection possible!',
        rating: '4.99',
    },
    {
        img: 'oil.png',
        imgAlt: 'oil',
        desc: 'Creativity stimulating lotion. Drink every morning to generate better ideas!',
        price: '$12.48',
        note: 'Worldwide shitting available. Buyers protection possible!',
        rating: '4.99',
    },
    {
        img: 'paper.png',
        imgAlt: 'paper',
        desc: 'Prototyping items to create a lot of useless things...',
        price: '$128.99',
        note: 'Showcasing onHovered state',
        rating: '4.87',
    },
    {
        img: 'pants.png',
        imgAlt: 'pants',
        desc: 'John Von Ebalkin SPRING',
        price: '$13.95',
        note: '1258 bids, 359 watchers $5.95 for shipping',
        rating: '4.56',
    },
    {
        img: 'notes.png',
        imgAlt: 'notes',
        desc: 'Envelope, Stripes, Pencil and etc. Purchase this kit today and feel OKAY',
        price: '$9.50',
        note: 'Eligible for Shipping To Mars or somewhere else',
        rating: '4.77',
    },
    {
        img: 'tea.png',
        imgAlt: 'tea',
        desc: 'Professional teadrinking set for every designer and developer',
        price: '$128.99',
        note: 'Eligible for nothing :(',
        rating: '4.87',
    },
    {
        img: 'flower.png',
        imgAlt: 'flower',
        desc: 'One string Bonsai description',
        price: '$11.68',
        note: 'Worldwide shitting available. Buyers protection possible!',
        rating: '4.99',
    },
    {
        img: 'lipstic.png',
        imgAlt: 'lipstic',
        desc: 'Simply best item in town to shine bright with your Nine Inch Nails',
        price: '$1.25',
        note: 'Eligible for Shipping To Mars or sominline-blockewhere else',
        rating: '4.77',
    },
    {
        img: 'brushes.png',
        imgAlt: 'brushes',
        desc: 'KISTOCHKI & KRASIBO. Top cosmetic brand from Chelyabinsk is here!',
        price: '$23.25',
        note: '1258 bids, 359 watchers $5.95 for shipping',
        rating: '4.56',
    },
    
]